import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const tema = {
  bg: '#1A1625',           
  bgSecundario: '#2D2640', 
  card: '#251E35',         
  cardClaro: '#342B45',    
  primary: '#C9A9A6',      
  secondary: '#B8A398',    
  accent: '#D4AFCD',       
  text: '#E8DFD0',         
  textSecundario: '#B5A89F',
  textFraco: '#8B7E7E',
  success: '#88B5A3',
  error: '#C98A8A',
  warning: '#D4BA8A',
  border: 'rgba(201, 169, 166, 0.25)',
};

export const estilos = StyleSheet.create({
  fundo: {
    flex: 1,
    backgroundColor: tema.bg,
  },
  container: {
    flex: 1,
    backgroundColor: tema.bg,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
  },
  scrollContainer: {
    flexGrow: 1,
    alignItems: 'center',
    paddingTop: 40,
    paddingBottom: 40,
    paddingHorizontal: 20,
  },

  headerContainer: {
    alignItems: 'center',
    marginBottom: 25,
    width: '100%',
  },
  iconeCoroa: {
    fontSize: 50,
    marginBottom: 10,
    opacity: 0.9,
  },
  tituloPrincipal: {
    fontSize: 42,
    fontWeight: '700',
    color: tema.text,
    letterSpacing: 4,
    textAlign: 'center',
    opacity: 0.95,
  },
  tituloSecundario: {
    fontSize: 32,
    fontWeight: '600',
    color: tema.primary,
    letterSpacing: 8,
    textAlign: 'center',
    marginTop: -5,
    opacity: 0.9,
  },
  divisorNeon: {
    width: 100,
    height: 2,
    backgroundColor: tema.primary,
    marginVertical: 12,
    borderRadius: 10,
    opacity: 0.6,
  },
  subtitulo: {
    fontSize: 15,
    color: tema.textSecundario,
    fontStyle: 'italic',
    textAlign: 'center',
    paddingHorizontal: 30,
    lineHeight: 22,
    opacity: 0.85,
  },

  bannerContainer: {
    width: '100%',
    height: 280,
    borderRadius: 20,
    overflow: 'hidden',
    marginBottom: 25,
    borderWidth: 1,
    borderColor: tema.border,
    backgroundColor: tema.card,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 5,
  },
  bannerImagem: {
    width: '100%',
    height: '100%',
  },
  bannerOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(26, 22, 37, 0.7)',
    justifyContent: 'flex-end',
    padding: 20,
  },
  bannerTexto: {
    fontSize: 16,
    color: tema.text,
    fontWeight: '500',
    fontStyle: 'italic',
    textAlign: 'center',
    opacity: 0.9,
  },

  cardPrincipal: {
    width: '100%',
    backgroundColor: tema.card,
    borderRadius: 20,
    padding: 20,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: tema.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 10,
    elevation: 6,
  },

  botaoPrimario: {
    backgroundColor: tema.primary,
    paddingVertical: 18,
    paddingHorizontal: 20,
    borderRadius: 15,
    marginBottom: 15,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.25,
    shadowRadius: 6,
    elevation: 5,
  },
  botaoConteudo: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 15,
  },
  botaoIcone: {
    fontSize: 28,
    opacity: 0.9,
  },
  textoBotaoPrimario: {
    color: tema.bg,
    fontSize: 18,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  botaoSubtexto: {
    color: tema.bgSecundario,
    fontSize: 12,
    fontWeight: '500',
    marginTop: 2,
    opacity: 0.85,
  },

  botaoSecundario: {
    backgroundColor: 'transparent',
    paddingVertical: 18,
    paddingHorizontal: 20,
    borderRadius: 15,
    borderWidth: 1.5,
    borderColor: tema.primary,
  },
  botaoIconeSecundario: {
    fontSize: 28,
    opacity: 0.9,
  },
  textoBotaoSecundario: {
    color: tema.primary,
    fontSize: 18,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  botaoSubtextoSecundario: {
    color: tema.textSecundario,
    fontSize: 12,
    fontWeight: '500',
    marginTop: 2,
    opacity: 0.8,
  },

  gridBotoes: {
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'space-between',
    marginBottom: 25,
    gap: 15,
  },
  botaoGrid: {
    flex: 1,
    backgroundColor: tema.cardClaro,
    paddingVertical: 22,
    paddingHorizontal: 10,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: tema.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 5,
    elevation: 3,
  },
  botaoGridIcone: {
    fontSize: 32,
    marginBottom: 8,
    opacity: 0.9,
  },
  botaoGridTexto: {
    color: tema.text,
    fontSize: 13,
    fontWeight: '600',
    textAlign: 'center',
    letterSpacing: 0.3,
    opacity: 0.9,
  },

  footerContainer: {
    width: '100%',
    paddingVertical: 18,
    paddingHorizontal: 20,
    backgroundColor: tema.cardClaro,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: tema.border,
  },
  dicaTexto: {
    color: tema.textSecundario,
    fontSize: 13,
    textAlign: 'center',
    fontStyle: 'italic',
    lineHeight: 19,
    opacity: 0.85,
  },

  feedbackCorreto: {
    borderColor: tema.success,
    borderWidth: 3,
    shadowColor: tema.success,
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 8,
  },
  feedbackErrado: {
    borderColor: tema.error,
    borderWidth: 3,
    shadowColor: tema.error,
    shadowOpacity: 0.4,
    shadowRadius: 8,
    elevation: 8,
  },

  cardContainer: {
    width: '100%',
    maxWidth: 400,
    backgroundColor: tema.card,
    borderRadius: 20,
    padding: 30,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: tema.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 6,
  },

  botao: {
    width: '100%',
    maxWidth: 300,
    paddingVertical: 15,
    paddingHorizontal: 20,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: tema.primary,
    marginTop: 15,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  textoBotao: {
    color: tema.text,
    fontSize: 16,
    fontWeight: '600',
    opacity: 0.9,
  },

  titulo: {
    fontSize: 36,
    fontWeight: '700',
    color: tema.primary,
    marginBottom: 5,
    textAlign: 'center',
    opacity: 0.95,
  },
  aviso: {
    color: tema.textFraco,
    fontSize: 12,
    marginTop: 20,
    textAlign: 'center',
    paddingHorizontal: 10,
    opacity: 0.8,
  },
});